### ISSUE TITLE
Simulate a 3-phase H Bridge + PWM current generator

### ISSUE THREAD

**Issue by MiniNugen** [MiniNugen/Custom_Inverter_Hardware#3]
A PWM controller is required to drive a 3-phase H-bridge setup. When done correctly, the output of each inverter phase should have a voltage level proportional to the duty cycle of the PWM controller. 

[This model is what my our inverter will be based on. So read this if you need extra resources](https://uwin365-my.sharepoint.com/:b:/g/personal/nguyen39_uwindsor_ca/EXIsp8yUNkpArx_SbNmMhxcB7SE95WXn12xlHMAQ0pFSlA?e=dWBUcs)

TLDR: Here's the plan, we'll need  3 PWM controllers. One for each phase. They will each receive an analog signal input between 2 to 12V. A 2V signal means the PWM is getting requested to generate a 0% duty cycle wave and a 12V means the PWM is getting requested to generate a 100% duty cycle wave. The wave will have ____Hz frequency (We'll decide on a frequency after we've established a speed requirement).  These PWM signals will be used to drive a Transistor array. Then the PWM signal is at 0% duty cycle, we should expect to see 0V at the output of that H-Bridge phase, When the PWM signal is at 100%, we should see our Power voltage at the output. 

When the Duty cycle is 0%, we would expect the overall voltage at that phase to be 0%

**Comment by Josh-Levesque** [comment]
[This model is what my our inverter will be based on. So read this if you need extra resources](https://uwin365-my.sharepoint.com/:b:/r/personal/nguyen39_uwindsor_ca/Documents/%5BFULLTEXT01.pdf%5D(https://uwin365-my.sharepoint.com/:b:/r/personal/nguyen39_uwindsor_ca/Documents/FULLTEXT01.pdf?csf=1&web=1&e=icIfjU)?csf=1&web=1&e=icIfjU)

This link is broken
